export const SET_AUTH = 'SET_AUTH';
export const ADD_USER = 'ADD_USER';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const ADD_CARTS = 'ADD_CARTS';
export const DELETE_CARTS = 'DELETE_CARTS';